name: grab-and-draw
on:
  schedule:
    - cron: "* * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.36.0"
      - run: ./grab.sh
      - run: ./render.sh
        continue-on-error: true
      - id: last-commit-message
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - if: steps.last-commit-message.outputs.msg != 'Grabbed & Rendered'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Grabbed & Rendered"
      - if: steps.last-commit-message.outputs.msg == 'Grabbed & Rendered'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Grabbed & Rendered"
          commit_options: "--amend --no-edit"
          push_options: "--force"
          skip_fetch: true
